version: "3"
services:
  roscore:
    build: ./roscore/
    volumes:
      - "./logs/roscore:/root/.ros/"
    command: stdbuf -o L roscore

  mavros:
    build: ./mavros/
    depends_on:
      - roscore
    volumes:
      - "./logs/mavros:/root/.ros/"
    environment:
      - "ROS_MASTER_URI=http://roscore:11311"

  arm:
    build: .
    depends_on:
      - roscore
      - mavros
    volumes:
      - "./logs/arm:/root/.ros/"
    environment:
      - "ROS_MASTER_URI=http://roscore:11311"
    command: ["stdbuf", "--output=L", "rosrun", "dr_hardware_tests", "arm.py"]

  box:
    build: .
    depends_on:
      - roscore
      - mavros
    volumes:
      - "./logs/box:/root/.ros/"
    environment:
      - "ROS_MASTER_URI=http://roscore:11311"
    command: ["stdbuf", "--output=L", "rosrun", "dr_hardware_tests", "box.py"]

  geofence:
    build: .
    depends_on:
      - roscore
      - mavros
    volumes:
      - "./logs/geofence:/root/.ros/"
    environment:
      - "ROS_MASTER_URI=http://roscore:11311"
    command: ["stdbuf", "--output=L", "rosrun", "dr_hardware_tests", "geofence.py"]

  gimbal:
    build: .
    depends_on:
      - roscore
      - mavros
    volumes:
      - "./logs/gimbal:/root/.ros/"
    environment:
      - "ROS_MASTER_URI=http://roscore:11311"
    command: ["stdbuf", "--output=L", "rosrun", "dr_hardware_tests", "gimbal.py"]

  hover:
    build: .
    depends_on:
      - roscore
      - mavros
    volumes:
      - "./logs/hover:/root/.ros/"
    environment:
      - "ROS_MASTER_URI=http://roscore:11311"
    command: ["stdbuf", "--output=L", "rosrun", "dr_hardware_tests", "hover.py"]

  indoor_sensors:
    build: .
    depends_on:
      - roscore
      - mavros
    environment:
      - "ROS_MASTER_URI=http://roscore:11311"
    volumes:
      - "./logs/indoor_sensors:/root/.ros/"
    command: ["stdbuf", "--output=L", "rosrun", "dr_hardware_tests", "indoor_sensors.py"]

  rc_failsafe:
    build: .
    depends_on:
      - roscore
      - mavros
    volumes:
      - "./logs/rc_failsafe:/root/.ros/"
    environment:
      - "ROS_MASTER_URI=http://roscore:11311"
    command: ["stdbuf", "--output=L", "rosrun", "dr_hardware_tests", "rc_failsafe.py"]

  sensors:
    build: .
    depends_on:
      - roscore
      - mavros
    volumes:
      - "./logs/sensors:/root/.ros/"
    environment:
      - "ROS_MASTER_URI=http://roscore:11311"
    command: ["stdbuf", "--output=L", "rosrun", "dr_hardware_tests", "sensors.py"]

  dev_test:
    build: .
    depends_on:
      - roscore
      - mavros
    environment:
      - "ROS_MASTER_URI=http://roscore:11311"
    volumes:
      - ./nodes:/opt/ros/noetic/lib/dr_hardware_tests
      - ./src/dr_hardware_tests/:/opt/ros/noetic/lib/python3/dist-packages/dr_hardware_tests
      - ./launch:/opt/ros/noetic/share/dr_hardware_tests/launch
      - "./logs/dev_test:/root/.ros/"
    command: ["stdbuf", "--output=L", "bash"]
