version: "3"
services:
  roscore:
    build: ./roscore/
    command: stdbuf -o L roscore
  
  mavlink_router:
    ports:
      - "5760:5760/tcp"
      - "5760:5760/udp"
    build: ./mavlink-router

  mavros:
    build: ./mavros/
    depends_on:
      - roscore
      - mavlink_router
    environment:
      - "ROS_MASTER_URI=http://roscore:11311"
    command: ["stdbuf", "-o", "L", "roslaunch", "--wait", "mavros", "px4.launch", "fcu_url:=udp://0.0.0.0:14555@mavlink_router:5760"]

  arm:
    build: .
    depends_on:
      - roscore
      - mavros
    environment:
      - "ROS_MASTER_URI=http://roscore:11311"
    command: ["stdbuf", "--output=L", "rosrun", "dr_hardware_tests", "arm.py"]

  box:
    build: .
    depends_on:
      - roscore
      - mavros
    environment:
      - "ROS_MASTER_URI=http://roscore:11311"
    command: ["stdbuf", "--output=L", "rosrun", "dr_hardware_tests", "box.py"]

  geofence:
    build: .
    depends_on:
      - roscore
      - mavros
    environment:
      - "ROS_MASTER_URI=http://roscore:11311"
    command: ["stdbuf", "--output=L", "rosrun", "dr_hardware_tests", "geofence.py"]

  gimbal:
    build: .
    depends_on:
      - roscore
      - mavros
    environment:
      - "ROS_MASTER_URI=http://roscore:11311"
    command: ["stdbuf", "--output=L", "rosrun", "dr_hardware_tests", "gimbal.py"]

  hover:
    build: .
    depends_on:
      - roscore
      - mavros
    environment:
      - "ROS_MASTER_URI=http://roscore:11311"
    command: ["stdbuf", "--output=L", "rosrun", "dr_hardware_tests", "hover.py"]

  indoor_sensors:
    build: .
    depends_on:
      - roscore
      - mavros
    environment:
      - "ROS_MASTER_URI=http://roscore:11311"
    command: ["stdbuf", "--output=L", "rosrun", "dr_hardware_tests", "indoor_sensors.py"]

  rc_failsafe:
    build: .
    depends_on:
      - roscore
      - mavros
    environment:
      - "ROS_MASTER_URI=http://roscore:11311"
    command: ["stdbuf", "--output=L", "rosrun", "dr_hardware_tests", "rc_failsafe.py"]

  sensors:
    build: .
    depends_on:
      - roscore
      - mavros
    environment:
      - "ROS_MASTER_URI=http://roscore:11311"
    command: ["stdbuf", "--output=L", "rosrun", "dr_hardware_tests", "sensors.py"]
