version: "3"
services:
  roscore:
    image: ros:noetic-ros-core
    expose:
      - "11311"
    command: stdbuf -o L roscore
    restart: always

  mavros:
    build: ./mavros/
    depends_on:
      - roscore
    environment:
      - "ROS_MASTER_URI=http://roscore:11311"
    restart: always

    # For companion computer
    # devices:
    #   - "/dev/ttyUSB0:/dev/ttyUSB0"
    # command: ["stdbuf", "--output=L", "roslaunch", "dr_hardware_tests", "mavros.launch", "fcu_url:=/dev/ttyUSB0:921600"]

    # For Simulator
    ports:
      - "14540:14540/udp"
    command: ["stdbuf", "-o", "L", "roslaunch", "mavros", "px4.launch", "fcu_url:=udp-b://:14540@14580"]
    
    # For Intel Aero
    # command: ["stdbuf", "-o", "L", "roslaunch", "mavros", "px4.launch", "fcu_url:=tcp://intel-aero:5760"]

  hardware_tests:
    build: .
    depends_on:
      - mavros
    environment:
      - "ROS_MASTER_URI=http://roscore:11311"
    links:
      - mavros

  arm:
    build: .
    depends_on:
      - mavros
    environment:
      - "ROS_MASTER_URI=http://roscore:11311"
    links:
      - mavros
    command: ["stdbuf", "--output=L", "rosrun", "dr_hardware_tests", "arm.py"]

  box:
    build: .
    depends_on:
      - mavros
    environment:
      - "ROS_MASTER_URI=http://roscore:11311"
    links:
      - mavros
    command: ["stdbuf", "--output=L", "rosrun", "dr_hardware_tests", "box.py"]
  
  geofence:
    build: .
    depends_on:
      - mavros
    environment:
      - "ROS_MASTER_URI=http://roscore:11311"
    links:
      - mavros
    command: ["stdbuf", "--output=L", "rosrun", "dr_hardware_tests", "geofence.py"]
  
  gimbal:
    build: .
    depends_on:
      - mavros
    environment:
      - "ROS_MASTER_URI=http://roscore:11311"
    links:
      - mavros
    command: ["stdbuf", "--output=L", "rosrun", "dr_hardware_tests", "gimbal.py"]
  
  hover:
    build: .
    depends_on:
      - mavros
    environment:
      - "ROS_MASTER_URI=http://roscore:11311"
    links:
      - mavros
    command: ["stdbuf", "--output=L", "rosrun", "dr_hardware_tests", "hover.py"] 

  indoor_sensors:
    build: .
    depends_on:
      - mavros
    environment:
      - "ROS_MASTER_URI=http://roscore:11311"
    links:
      - mavros
    command: ["stdbuf", "--output=L", "rosrun", "dr_hardware_tests", "indoor_sensors.py"]

  rc_failsafe:
    build: .
    depends_on:
      - mavros
    environment:
      - "ROS_MASTER_URI=http://roscore:11311"
    links:
      - mavros
    command: ["stdbuf", "--output=L", "rosrun", "dr_hardware_tests", "rc_failsafe.py"]

  sensors:
    build: .
    depends_on:
      - mavros
    environment:
      - "ROS_MASTER_URI=http://roscore:11311"
    links:
      - mavros
    command: ["stdbuf", "--output=L", "rosrun", "dr_hardware_tests", "sensors.py"]
  
