version: '3'
services:
  mavros:
    # For companion computer
    devices:
      - "/dev/ttyUSB0:/dev/ttyUSB0"
    command: ["stdbuf", "-o", "L", "roslaunch", "mavros", "px4.launch", "fcu_url:=/dev/ttyUSB0:921600"]